(function(N){var D=N.DATA;var E=N.E;var S=E.S;
function $(id){return document.getElementById(id);}
function h(tag,attrs,inner){var s="<"+tag;if(attrs){var k=Object.keys(attrs);for(var i=0;i<k.length;i++)s+=" "+k[i]+'="'+attrs[k[i]]+'"';}if(inner===undefined||inner===null)return s+"/>";return s+">"+inner+"</"+tag+">";}
function sel(id,opts,val,cls){var o="";for(var i=0;i<opts.length;i++){var ov=opts[i];o+="<option value=\""+ov.v+"\""+(ov.v===val?" selected":"")+">"+ov.l+"</option>";}return '<select id="'+id+'" class="nv-select '+(cls||"")+'" data-prev="'+val+'">'+o+"</select>";}
var toastTimer=null;
function toast(msg,type){var el=$("toast");if(!el)return;el.textContent=msg;el.className="toast toast-"+(type||"info")+" toast-show";clearTimeout(toastTimer);toastTimer=setTimeout(function(){el.classList.remove("toast-show");},2500);}
N.toast=toast;
function tipText(el){var t=el.getAttribute("data-tip");return t||"";}
function initTooltips(){var tip=document.createElement("div");tip.id="globalTip";tip.style.cssText="position:fixed;z-index:9999;background:#1a1e30;color:#e0e4f0;border:1px solid #6c8cff;border-radius:6px;padding:6px 10px;font-size:.78rem;max-width:300px;pointer-events:none;opacity:0;transition:opacity .15s;line-height:1.4;box-shadow:0 4px 16px rgba(0,0,0,.5)";document.body.appendChild(tip);
document.addEventListener("mouseover",function(e){var t=e.target;if(!t)return;var el=t.closest?t.closest("[data-tip]"):null;if(!el)return;var text=el.getAttribute("data-tip");if(!text)return;tip.textContent=text;tip.style.opacity="1";var r=el.getBoundingClientRect();var tx=r.left;var ty=r.top-8;tip.style.transform="translateY(-100%)";if(tx+310>window.innerWidth)tx=window.innerWidth-320;if(tx<4)tx=4;tip.style.left=tx+"px";tip.style.top=ty+"px";});
document.addEventListener("mouseout",function(e){if(!e.target)return;var el=e.target.closest?e.target.closest("[data-tip]"):null;if(el){tip.style.opacity="0";}});}
function initAccordions(){document.querySelectorAll(".acc-header").forEach(function(hd){hd.addEventListener("click",function(){var acc=this.parentElement;var bd=acc.querySelector(".acc-body");var arrow=this.querySelector(".acc-arrow");if(bd.style.display==="none"){bd.style.display="block";if(arrow)arrow.textContent="\u25BC";}else{bd.style.display="none";if(arrow)arrow.textContent="\u25B6";}});});}
function accordion(title,id,content,open){var disp=open?"block":"none";var arrow=open?"\u25BC":"\u25B6";return '<div class="accordion" id="'+id+'"><div class="acc-header"><span class="acc-arrow">'+arrow+'</span><span class="acc-title">'+title+'</span></div><div class="acc-body" style="display:'+disp+'">'+content+'</div></div>';}
function meterHTML(id,label,tip){return '<div class="meter-wrap"><span class="meter-label has-tip" data-tip="'+(tip||"")+'">'+label+'</span><div class="meter-bar"><div class="meter-fill" id="fill_'+id+'"></div></div><span class="meter-val" id="val_'+id+'">0</span></div>';}
function setMeter(id,val){var fill=$("fill_"+id);var valEl=$("val_"+id);if(!fill||!valEl)return;var p=Math.round(val*100);fill.style.width=p+"%";var neg=id.indexOf("tension")>=0||id.indexOf("friction")>=0||id.indexOf("rejSens")>=0||id.indexOf("stress")>=0;var color;if(neg){color=p<=30?"var(--pos)":p<=50?"#8ecae6":p<=65?"var(--warn)":"var(--neg)";}else{color=p>=70?"var(--pos)":p>=50?"#8ecae6":p>=35?"var(--warn)":"var(--neg)";}fill.style.background=color;valEl.textContent=p+"%";valEl.style.color=color;}

function radarSVG(who){var radar=E.calcRadar(who);var cx=100,cy=95,maxR=70,n=8;var svg='<svg class="radar-svg" viewBox="0 0 200 200">';for(var r=17;r<=maxR;r+=17){svg+='<circle cx="'+cx+'" cy="'+cy+'" r="'+r+'" class="radar-ring"/>';}var pts=[];for(var i=0;i<n;i++){var ang=(Math.PI*2/n)*i-Math.PI/2;var ex=cx+Math.cos(ang)*maxR;var ey=cy+Math.sin(ang)*maxR;svg+='<line x1="'+cx+'" y1="'+cy+'" x2="'+E.rnd(ex,1)+'" y2="'+E.rnd(ey,1)+'" class="radar-spoke"/>';var lx=cx+Math.cos(ang)*(maxR+16);var ly=cy+Math.sin(ang)*(maxR+16);var v=radar[D.DIM_KEYS[i]]||.5;var anchor="middle";if(Math.cos(ang)>.3)anchor="start";if(Math.cos(ang)<-.3)anchor="end";svg+='<text x="'+E.rnd(lx,0)+'" y="'+E.rnd(ly,0)+'" class="radar-label" text-anchor="'+anchor+'" dominant-baseline="middle">'+D.DIM_LABELS[i]+" "+D.pct(v)+"%</text>";pts.push([cx+Math.cos(ang)*maxR*v,cy+Math.sin(ang)*maxR*v]);}var poly="";for(var i=0;i<pts.length;i++)poly+=E.rnd(pts[i][0],1)+","+E.rnd(pts[i][1],1)+" ";svg+='<polygon points="'+poly+'" class="radar-data"/>';for(var i=0;i<pts.length;i++){svg+='<circle cx="'+E.rnd(pts[i][0],1)+'" cy="'+E.rnd(pts[i][1],1)+'" r="3" fill="var(--accent)"/>';}svg+="</svg>";return svg;}

function relRadarSVG(){var vals=E.calcRelRadar();var cx=110,cy=105,maxR=80,n=D.REL_RADAR_KEYS.length;var svg='<svg class="rel-radar-svg" viewBox="0 0 220 220">';for(var r=20;r<=maxR;r+=20){svg+='<circle cx="'+cx+'" cy="'+cy+'" r="'+r+'" class="radar-ring"/>';}var pts=[];for(var i=0;i<n;i++){var ang=(Math.PI*2/n)*i-Math.PI/2;var ex=cx+Math.cos(ang)*maxR;var ey=cy+Math.sin(ang)*maxR;svg+='<line x1="'+cx+'" y1="'+cy+'" x2="'+E.rnd(ex,1)+'" y2="'+E.rnd(ey,1)+'" class="radar-spoke"/>';var lx=cx+Math.cos(ang)*(maxR+18);var ly=cy+Math.sin(ang)*(maxR+18);var v=vals[i]||.5;var anchor="middle";if(Math.cos(ang)>.3)anchor="start";if(Math.cos(ang)<-.3)anchor="end";svg+='<text x="'+E.rnd(lx,0)+'" y="'+E.rnd(ly,0)+'" class="radar-label" text-anchor="'+anchor+'" dominant-baseline="middle">'+D.REL_RADAR_LABELS[i]+" "+D.pct(v)+"%</text>";pts.push([cx+Math.cos(ang)*maxR*v,cy+Math.sin(ang)*maxR*v]);}var poly="";for(var i=0;i<pts.length;i++)poly+=E.rnd(pts[i][0],1)+","+E.rnd(pts[i][1],1)+" ";svg+='<polygon points="'+poly+'" class="radar-data"/>';for(var i=0;i<pts.length;i++){svg+='<circle cx="'+E.rnd(pts[i][0],1)+'" cy="'+E.rnd(pts[i][1],1)+'" r="3" fill="var(--accent)"/>';}svg+="</svg>";return svg;}

function statusBarHTML(){var ov=S.rel.overall||0;var tier=D.getTier(ov,D.REL_TIERS);var pct=Math.round(ov*100);var descs={Flourishing:"Deeply connected, safe, and growing together.",Healthy:"Solid foundation with good communication.",Stable:"Functioning well with areas to strengthen.",Strained:"Noticeable tension. Address issues early.",Distressed:"Significant problems. Support recommended.",Critical:"Severe dysfunction. Professional help recommended.",Collapsed:"Relationship has broken down."};var desc=descs[tier.label]||"";return '<div class="status-bar-wrap"><div class="status-bar-label" style="color:'+tier.color+'">'+tier.label+' ('+pct+'%)</div><div class="status-bar"><div class="status-dot" style="left:'+pct+'%" data-tip="'+tier.label+': '+pct+'%. '+desc+'"></div></div><div class="status-detail">Relationship Health</div></div>';}
function buildProfilePanel(who){var p=S[who];var s=who==="a"?"A":"B";var mbtiOpts=Object.keys(D.MBTI).map(function(k){return{v:k,l:D.MBTI[k].label};});var enneaOpts=Object.keys(D.ENNEA).map(function(k){return{v:k,l:D.ENNEA[k].label};});var attOpts=Object.keys(D.ATT).map(function(k){return{v:k,l:D.ATT[k].label};});var llOpts=D.LL_LIST.map(function(k){return{v:k,l:D.LL_LABELS[k]};});var confOpts=Object.keys(D.CONFLICT).map(function(k){return{v:k,l:D.CONFLICT[k].label};});var moodOpts=Object.keys(D.MOOD).map(function(k){return{v:k,l:k.charAt(0).toUpperCase()+k.slice(1)};});
var html='<div class="profile-panel"><div class="profile-title" id="hd'+s+'">'+p.name+' <button class="wiz-top-btn" data-who="'+who+'" title="Setup Wizard">\uD83E\uDDD9</button></div>';
html+='<div class="field-row"><span class="field-label">Name</span><input type="text" id="name'+s+'" value="'+p.name+'" class="nv-input" data-field="name" data-who="'+who+'"></div>';
html+='<div class="field-row"><span class="field-label has-tip" data-tip="Myers-Briggs Type Indicator \u2014 16 personality types.">MBTI</span>'+sel("mbti"+s,mbtiOpts,p.mbti,"profile-sel")+'<button class="wiz-field-btn" onclick="Novus.openWizField(\''+who+'\',\'mbti\')" title="Help me find my type">\uD83E\uDDD9</button><div class="sel-tip" id="tip_mbti'+s+'"></div></div>';
html+='<div class="field-row"><span class="field-label has-tip" data-tip="Enneagram \u2014 9 core personality types by motivation.">Enneagram</span>'+sel("ennea"+s,enneaOpts,p.ennea,"profile-sel")+'<button class="wiz-field-btn" onclick="Novus.openWizField(\''+who+'\',\'ennea\')" title="Help me find my type">\uD83E\uDDD9</button><div class="sel-tip" id="tip_ennea'+s+'"></div></div>';
html+='<div class="field-row"><span class="field-label has-tip" data-tip="Attachment style \u2014 strongest single predictor of relationship quality.">Attachment</span>'+sel("attach"+s,attOpts,p.attach,"profile-sel")+'<button class="wiz-field-btn" onclick="Novus.openWizField(\''+who+'\',\'attach\')" title="Help me find my style">\uD83E\uDDD9</button><div class="sel-tip" id="tip_attach'+s+'"></div></div>';
html+='<div class="field-row"><span class="field-label has-tip" data-tip="How this person typically expresses love to their partner.">Gives Love As</span>'+sel("llGive"+s,llOpts,p.llGive||p.ll||"time","profile-sel")+'</div>';
html+='<div class="field-row"><span class="field-label has-tip" data-tip="How this person most feels loved when their partner does this.">Receives Love As</span>'+sel("llReceive"+s,llOpts,p.llReceive||p.ll||"time","profile-sel")+'</div>';
html+='<div class="field-row"><span class="field-label has-tip" data-tip="Conflict style \u2014 based on Gottman research.">Conflict Style</span>'+sel("conflict"+s,confOpts,p.conflict,"profile-sel")+'<div class="sel-tip" id="tip_conflict'+s+'"></div></div>';
html+='<div class="field-row"><span class="field-label has-tip" data-tip="Current mood state \u2014 temporarily influences all interactions.">Mood</span>'+sel("mood"+s,moodOpts,p.mood,"profile-sel")+'<div class="sel-tip" id="tip_mood'+s+'"></div></div>';
html+='<div class="field-row"><span class="field-label has-tip" data-tip="Support network \u2014 external support from friends, family, community.">Support Network</span><input type="range" id="support'+s+'" value="'+p.support+'" min="0" max="100" class="nv-slider" data-field="support" data-who="'+who+'" style="flex:1"><span class="slider-val" id="supportVal'+s+'">'+D.getSupportLabel(p.support).label+'</span></div><div class="sel-tip" id="supportTip'+s+'" style="display:block;color:var(--text2);font-size:.72rem">'+D.getSupportLabel(p.support).desc+'</div>';
html+="</div>";return html;}
function buildOcean(who){var s=who==="a"?"A":"B";var traits=[["O","Openness"],["C","Conscientiousness"],["E","Extraversion"],["A","Agreeableness"],["N","Neuroticism"]];var html='<div class="ocean-group">';for(var i=0;i<traits.length;i++){var t=traits[i];var v=Math.round((S[who].ocean[t[0]]||.5)*100);html+='<div class="slider-wrap"><span class="slider-label">'+t[1]+'</span><input type="range" min="0" max="100" value="'+v+'" class="nv-slider" data-who="'+who+'" data-trait="'+t[0]+'" id="ocean_'+t[0]+s+'"><span class="slider-val" id="ov_'+t[0]+s+'">'+v+'</span></div>';}html+="</div>";return html;}
function buildMH(who){var s=who==="a"?"A":"B";var html='<div class="mh-section"><div class="mh-header"><div class="mh-hdr-cell">Diagnosis</div><div class="mh-hdr-cell">Intensity</div><div class="mh-hdr-cell">Selected</div></div>';for(var i=0;i<D.MH_ORDER.length;i++){var k=D.MH_ORDER[i];var def=D.MH[k];if(!def)continue;var v=S[who].mh[k]||0;var lvlInfo=D.MH_LEVELS[v];var tip=def.selfTip+" | "+def.partnerTip+" | Engine: "+def.engTip;html+='<div class="mh-row"><span class="mh-name has-tip" data-tip="'+tip.replace(/"/g,"&quot;")+'">'+def.label+'</span><div class="mh-slider-wrap"><input type="range" min="0" max="9" value="'+v+'" class="nv-slider" data-who="'+who+'" data-mhkey="'+k+'" id="mh_'+k+s+'"><div class="slider-tip" id="mhtip_'+k+s+'">'+(v>0?lvlInfo.label+": "+lvlInfo.desc:"")+'</div></div><span class="mh-selected-val" id="mhval_'+k+s+'">'+v+'</span></div>';}html+="</div>";return html;}
function buildIndMeters(who){var s=who==="a"?"A":"B";var html="";html+=meterHTML("emReg"+s,"Emotion Regulation",D.TIP.emotionRegulation);html+=meterHTML("worth"+s,"Self-Worth",D.TIP.selfWorth);html+=meterHTML("secure"+s,"Security w/ Partner",D.TIP.secureWithPartner);html+=meterHTML("hope"+s,"Hope",D.TIP.hope);html+=meterHTML("rejSens"+s,"Rejection Sensitivity",D.TIP.rejectionSensitivity);html+=meterHTML("trustP"+s,"Trust in Partner",D.TIP.trustInPartner);html+=meterHTML("stress"+s,"External Stress",D.TIP.externalStress);html+=meterHTML("expect"+s,"Self-Expectations",D.TIP.selfExpectations);html+=meterHTML("health"+s,"Overall Health",D.TIP.health);html+=meterHTML("intim"+s,"Intimacy",D.TIP.intimacy);html+=meterHTML("wot"+s,"Window of Tolerance",D.TIP.windowOfTolerance);
html+='<div class="section-title" style="margin-top:8px">Emotional State</div><div id="emotState'+s+'" class="info-card"></div>';
html+='<div class="section-title" style="margin-top:8px">Body Response</div><div id="bioMetrics'+s+'" class="info-card"></div>';
html+='<div class="section-title" style="margin-top:8px">Suggestions</div><div id="indRecs'+s+'"></div>';
return html;}
function buildRelMeters(){var html="";html+=meterHTML("rSafety","Safety",D.TIP.safety);html+=meterHTML("rTrust","Trust",D.TIP.trust);html+=meterHTML("rBond","Bond",D.TIP.bond);html+=meterHTML("rConn","Connection",D.TIP.connection);html+=meterHTML("rMeaning","Meaning",D.TIP.meaning);html+=meterHTML("rHonesty","Honesty",D.TIP.honesty);html+=meterHTML("rStab","Stability",D.TIP.stability);html+=meterHTML("rIntim","Intimacy",D.TIP.intimacy);html+=meterHTML("rGrowth","Growth",D.TIP.growth);html+=meterHTML("rTension","Tension",D.TIP.tension);html+=meterHTML("rFriction","Friction",D.TIP.friction);html+=meterHTML("rPassion","Passion",D.TIP.passion);html+=meterHTML("rCommit","Commitment",D.TIP.commitment);html+=meterHTML("rSternInt","Emotional Intimacy",D.TIP.sternIntimacy);html+=meterHTML("rOverall","Overall",D.TIP.overall);return html;}
function buildRelRadarSection(){return '<div id="relRadarBox" style="margin-top:8px"></div>';}
function buildRelRecsSection(){return '<div class="section-title">Recommendations</div><div id="recs"></div>';}

function renderIndMetrics(who){var p=S[who];var s=who==="a"?"A":"B";setMeter("emReg"+s,p.emotionRegulation);setMeter("worth"+s,p.selfWorth);setMeter("secure"+s,p.secureWithPartner);setMeter("hope"+s,p.hope);setMeter("rejSens"+s,p.rejectionSensitivity);setMeter("trustP"+s,p.trustInPartner);setMeter("stress"+s,p.externalStress);setMeter("expect"+s,p.selfExpectations);setMeter("health"+s,p.health);setMeter("intim"+s,p.intimacy);setMeter("wot"+s,p.wot||.5);
var dosEl=$("dos"+s);if(dosEl){var bw=E.calcBowen(p);dosEl.innerHTML="<strong>Differentiation:</strong> "+E.bowenLabel(bw.dos)+" ("+D.pct(bw.dos)+"%)";}
var drEl=$("drift"+s);if(drEl){var dk=who==="a"?S.driftA:S.driftB;if(dk.score!==0){drEl.innerHTML="Attachment drift: <strong>"+dk.dir+"</strong> ("+E.rnd(dk.score,1)+")";drEl.style.display="block";}else{drEl.innerHTML="";drEl.style.display="none";}}
var satirEl=$("satir"+s);if(satirEl){var stance=p.satirStance||"congruent";var sl=D.SATIR.labels[stance]||stance;var sd=D.SATIR.desc[stance]||"";satirEl.innerHTML="<strong>Communication:</strong> "+sl+'<div style="font-size:.72rem;color:var(--text2);margin-top:2px">'+sd+"</div>";}
var vagalEl=$("vagal"+s);if(vagalEl){var vs=p.vagalState||"ventral";var vl=D.POLYVAGAL.labels[vs]||vs;var clr=vs==="ventral"?"var(--pos)":vs==="sympathetic"?"var(--warn)":"var(--neg)";vagalEl.innerHTML='<strong>Nervous System:</strong> <span style="color:'+clr+'">'+vl+"</span>";}
var seEl=$("sentiment"+s);if(seEl){var ws=E.calcWSent();var lbl=ws>.3?"Positive":ws<-.3?"Negative":"Neutral";if(S.evtCount>0){seEl.innerHTML="Emotional trend: <strong>"+lbl+"</strong>";seEl.style.display="block";}else{seEl.innerHTML="";seEl.style.display="none";}}}
function renderRelMetrics(){var r=S.rel;setMeter("rSafety",r.safety);setMeter("rTrust",r.trust);setMeter("rBond",r.bond);setMeter("rConn",r.connection);setMeter("rMeaning",r.meaning);setMeter("rHonesty",r.honesty);setMeter("rStab",r.stability);setMeter("rIntim",r.intimacy);setMeter("rGrowth",r.growth);setMeter("rTension",r.tension);setMeter("rFriction",r.friction);setMeter("rPassion",r.passion);setMeter("rCommit",r.commitment);setMeter("rSternInt",r.sternIntimacy);setMeter("rOverall",r.overall);
var stEl=$("relStatus");if(stEl){var t=D.getTier(r.overall,D.REL_TIERS);stEl.innerHTML='<strong>Status:</strong> <span style="color:'+t.color+'">'+t.label+"</span> ("+D.pct(r.overall)+"%)";}
var relEsEl=$("relEmotState");if(relEsEl&&E.getRelEmotionalState){var res=E.getRelEmotionalState();var psoColor=res.pso.indexOf("Positive")>=0?"var(--pos)":res.pso.indexOf("Negative")>=0?"var(--neg)":"var(--text2)";relEsEl.innerHTML='<div class="state-row"><span class="state-label">Status</span><span class="state-val" style="color:'+(D.getTier(res.overallVal,D.REL_TIERS).color||"var(--text)")+'">'+res.overall+' ('+D.pct(res.overallVal)+'%)</span></div><div class="state-row"><span class="state-label">Tension</span><span class="state-val">'+res.tension+'</span></div><div class="state-row"><span class="state-label has-tip" data-tip="The overall emotional climate. Positive means good events outweigh bad. Negative means small problems feel bigger.">Climate</span><span class="state-val" style="color:'+psoColor+'">'+res.pso+' ('+D.pct(res.psoRatio)+')</span></div><div class="state-row"><span class="state-label has-tip" data-tip="'+res.loveDesc+'">Love Type</span><span class="state-val" style="color:'+res.loveColor+'">'+res.loveType+'</span></div><div class="state-row"><span class="state-label">Conflict Level</span><span class="state-val">'+(res.conflictLvl<=1?"Low":res.conflictLvl<=3?"Moderate":"High")+' ('+Math.round(res.conflictLvl)+'/6)</span></div>';}
var stbEl=$("sternbergBox");if(stbEl){var st=E.classifySternberg(r.sternIntimacy,r.passion,r.commitment);stbEl.innerHTML='<strong>Love Type:</strong> <span style="color:'+st.color+'">'+st.type+"</span><br><small>"+st.desc+"</small>";}
var ruEl=$("rusbultBox");if(ruEl){var rb=E.calcRusbult();if(S.evtCount>0){ruEl.innerHTML="<strong>Commitment Model:</strong> Satisfaction: "+D.pct(rb.sat)+"% | Investment: "+D.pct(rb.inv)+"% | Alternatives: "+D.pct(rb.alt)+"%";ruEl.style.display="block";}}
var psoEl=$("psoBox");if(psoEl){var pso=E.calcPSO();var lbl=pso.mode==="positive"?"Positive Override \u2713":pso.mode==="negative"?"Negative Override \u2717":"Neutral";var clr=pso.mode==="positive"?"var(--pos)":pso.mode==="negative"?"var(--neg)":"var(--text2)";psoEl.innerHTML='<span style="color:'+clr+'">'+lbl+"</span> ("+Math.round(pso.ratio*100)+"% positive)";if(S.evtCount>0)psoEl.style.display="block";}
var repEl=$("repairBox");if(repEl){if(S.repairWin.active){repEl.innerHTML='<span style="color:var(--warn)">\u26A0 Repair Window: '+S.repairWin.remaining+" events left</span>";repEl.style.display="block";}else{repEl.innerHTML="";repEl.style.display="none";}}
var confEl=$("conflictBox");if(confEl){if(S.conflictLvl>0){var labels=["Calm","Mild","Rising","Active","Heated","Escalated","Crisis"];confEl.innerHTML="Conflict: <strong>"+labels[Math.min(Math.round(S.conflictLvl),6)]+"</strong> ("+Math.round(S.conflictLvl)+"/6)";confEl.style.display="block";}else{confEl.innerHTML="";confEl.style.display="none";}}
var comboEl=$("comboBox");if(comboEl){var combo=D.getAttCombo(S.a.attach,S.b.attach);comboEl.innerHTML='<strong>Dynamic:</strong> '+combo.label+'<div style="font-size:.72rem;color:var(--text2);margin-top:2px">'+combo.dynamics+" (Risk: "+D.pct(combo.risk)+"%)</div>";}}
function renderStory(who){var p=S[who];var s=who==="a"?"A":"B";var el=$("story"+s);if(!el)return;var mbti=D.MBTI[p.mbti]||{label:p.mbti};var enn=D.ENNEA[p.ennea]||{label:p.ennea};var att=D.ATT[p.attach]||{label:p.attach};var tier=D.getTier(p.health,D.IND_TIERS);var bw=E.calcBowen(p);var h="<strong>"+p.name+"</strong> \u2014 "+mbti.label+", Enneagram "+enn.label;h+=". Attachment: <em>"+att.label+"</em>.";h+='<br>Health: <span style="color:'+tier.color+'">'+tier.label+"</span> ("+D.pct(p.health)+"%)";var wotL=D.getWotLabel?D.getWotLabel(p.wot):{label:"",desc:"",clinical:""};var vagF=D.VAGAL_FRIENDLY?D.VAGAL_FRIENDLY[p.vagalState]:{label:p.vagalState,desc:"",clinical:""};var satF=D.SATIR_FRIENDLY?D.SATIR_FRIENDLY[p.satirStance]:{label:p.satirStance,desc:"",clinical:""};
h+="<br><span class=\"has-tip\" data-tip=\""+E.bowenLabel(bw.dos)+" ("+D.pct(bw.dos)+"%). How well this person maintains their sense of self under pressure.\">Independence: "+E.bowenLabel(bw.dos)+"</span>";
h+="<br><span class=\"has-tip\" data-tip=\""+vagF.clinical+". "+vagF.desc+"\">Nervous System: "+vagF.label+"</span>";
h+="<br><span class=\"has-tip\" data-tip=\""+satF.clinical+". "+satF.desc+"\">Communication: "+satF.label+"</span>";
h+="<br><span class=\"has-tip\" data-tip=\""+wotL.clinical+". "+wotL.desc+"\">Stress Tolerance: "+wotL.label+"</span>";if(att.desc)h+="<br><small>"+att.desc+"</small>";el.innerHTML=h;}
function renderNarrative(){var el=$("relNarrative");if(!el)return;if(!S.evtCount){el.innerHTML='<span class="empty-msg">Process interactions to generate narrative.</span>';return;}var r=S.rel;var tier=D.getTier(r.overall,D.REL_TIERS);var pso=E.calcPSO();var combo=D.getAttCombo(S.a.attach,S.b.attach);var st=E.classifySternberg(r.sternIntimacy,r.passion,r.commitment);var h="<strong>"+S.a.name+" & "+S.b.name+'</strong> \u2014 <span style="color:'+tier.color+'">'+tier.label+"</span> ("+D.pct(r.overall)+"%)";h+="<br><strong>Dynamic:</strong> "+combo.label+" \u2014 "+combo.dynamics;h+="<br><strong>Love Type:</strong> "+st.type;h+="<br><strong>Climate:</strong> ";if(pso.mode==="positive")h+="Positive \u2014 the relationship absorbs negativity well right now.";else if(pso.mode==="negative")h+="Negative \u2014 even small negatives hit harder right now.";else h+="Balanced \u2014 neither buffering nor amplifying negative events.";var keyItems="";if(r.trust<.40)keyItems+="\u2022 Trust is critically low ("+D.pct(r.trust)+"%).<br>";if(r.tension>.60)keyItems+="\u2022 Tension is high ("+D.pct(r.tension)+"%).<br>";if(r.safety<.40)keyItems+="\u2022 Emotional safety needs attention.<br>";if(r.passion<.30)keyItems+="\u2022 Passion has faded significantly.<br>";if(r.bond>.70)keyItems+="\u2022 Strong emotional bond is a source of resilience.<br>";if(S.conflictLvl>3)keyItems+="\u2022 Conflict is escalating (Level "+Math.round(S.conflictLvl)+"/6). De-escalation is important.<br>";if(S.repairWin.active)keyItems+="\u2022 \u26A0 Repair window is open \u2014 repair attempts are twice as effective right now!<br>";if(keyItems)h+="<br><strong>Key Observations:</strong><br>"+keyItems;el.innerHTML=h;}
function renderRecs(){var el=$("recs");if(!el)return;var recs=E.getRelRecs?E.getRelRecs():[];if(!recs.length){el.innerHTML='<span class="empty-msg">No specific recommendations at this time.</span>';return;}var h="";for(var i=0;i<recs.length;i++){h+='<div class="rec-item"><span class="rec-emoji">'+recs[i].emoji+'</span><span class="rec-text">'+recs[i].text+'</span></div>';}el.innerHTML=h;}
function renderLog(elId,entries){var el=$(elId);if(!el)return;if(!entries||!entries.length){el.innerHTML='<span class="empty-msg">No events yet.</span>';return;}var h="";for(var i=entries.length-1;i>=0;i--){h+='<div class="log-entry">['+entries[i].time+"] "+entries[i].msg+"</div>";}el.innerHTML=h;}
function renderTimeline(){var el=$("timelineBox");if(!el)return;if(S.history.length<2){el.innerHTML='<span class="empty-msg">Process events to build timeline.</span>';return;}var w=500,ht=200,pad=30;var n=S.history.length;var stepX=(w-pad*2)/(n-1);var svg='<svg class="timeline-svg" viewBox="0 0 '+w+" "+ht+'">';for(var g=0;g<=100;g+=25){var gy=pad+(1-g/100)*(ht-pad*2);svg+='<line x1="'+pad+'" y1="'+gy+'" x2="'+(w-pad)+'" y2="'+gy+'" stroke="rgba(255,255,255,.06)"/>';svg+='<text x="'+(pad-3)+'" y="'+gy+'" fill="var(--text2)" font-size="7" text-anchor="end" dominant-baseline="middle">'+g+"</text>";}var lines=[{key:"relHealth",color:"var(--accent)"},{key:"healthA",color:"var(--pos)"},{key:"healthB",color:"#a78bfa"}];for(var li=0;li<lines.length;li++){var path="M";for(var i=0;i<n;i++){var x=pad+i*stepX;var y=pad+(1-S.history[i][lines[li].key])*(ht-pad*2);path+=(i===0?"":" L")+E.rnd(x,1)+","+E.rnd(y,1);}svg+='<path d="'+path+'" fill="none" stroke="'+lines[li].color+'" stroke-width="1.5" opacity=".8"/>';}for(var i=0;i<n;i++){var x=pad+i*stepX;var y=pad+(1-S.history[i].relHealth)*(ht-pad*2);svg+='<circle cx="'+E.rnd(x,1)+'" cy="'+E.rnd(y,1)+'" r="3" fill="var(--accent)" opacity=".7" data-tip="'+S.history[i].label+" | "+D.pct(S.history[i].relHealth)+'%" style="cursor:pointer"/>';}svg+="</svg>";var legend='<div class="tl-legend"><span><span class="tl-legend-dot" style="background:var(--accent)"></span>Relationship</span><span><span class="tl-legend-dot" style="background:var(--pos)"></span>'+S.a.name+'</span><span><span class="tl-legend-dot" style="background:#a78bfa"></span>'+S.b.name+'</span></div>';el.innerHTML=svg+legend;}

function showEventSummary(result){if(!result)return;var el=$("eventBody");if(!el)return;var h="<strong>"+result.action+"</strong> @ "+D.pct(result.intensity)+"%";h+="<br>Vuln: "+result.vulnScale+"x | Frag: "+result.fragScale+"x | Conflict: Lv"+Math.round(result.conflictLevel);h+="<br>Satir: "+D.SATIR.labels[result.satirA]+" | Vagal: "+D.POLYVAGAL.labels[result.vagalA];var sections=[{label:S[result.actor].name+" (Self)",data:result.selfImpact,color:"var(--accent)"},{label:S[result.receiver].name+" (Partner x"+result.vulnScale+")",data:result.partnerImpact,color:"#a78bfa"},{label:"Relationship (x"+result.fragScale+")",data:result.relImpact,color:"var(--warn)"}];for(var si=0;si<sections.length;si++){if(!sections[si].data)continue;h+='<br><strong style="color:'+sections[si].color+'">'+sections[si].label+"</strong><br>";var keys=Object.keys(sections[si].data);for(var i=0;i<keys.length;i++){var v=sections[si].data[keys[i]];if(v===0)continue;var clr=v>0?"var(--pos)":"var(--neg)";h+='<span style="color:'+clr+'">'+D.friendly(keys[i])+": "+(v>0?"+":"")+D.pct(v)+"%</span> ";}}el.innerHTML=h;$("eventModal").style.display="flex";}
function populateCats(selId){var el=$(selId);if(!el)return;el.innerHTML='<option value="">-- Select --</option>';for(var i=0;i<D.CAT_ORDER.length;i++){el.innerHTML+='<option value="'+D.CAT_ORDER[i]+'">'+D.CAT_ORDER[i]+"</option>";}}
function populateScens(catKey,selId){var el=$(selId);if(!el)return;el.innerHTML='<option value="">-- Select Category --</option>';var cat=D.INTERACTIONS[catKey];if(!cat)return;for(var i=0;i<cat.scenarios.length;i++){el.innerHTML+='<option value="'+i+'">'+cat.scenarios[i].label+"</option>";}}
function buildInteractionPanel(){var html='<div class="interaction-panel">';html+='<div class="int-controls"><span class="int-label">Direction</span><select id="ibDir" class="nv-select"><option value="AtoB">'+S.a.name+" \u2192 "+S.b.name+'</option><option value="BtoA">'+S.b.name+" \u2192 "+S.a.name+"</option></select></div>";html+='<div class="int-controls"><span class="int-label">Category</span><select id="ibCat" class="nv-select"><option value="">-- Select --</option></select></div>';html+='<div class="int-controls"><span class="int-label">Scenario</span><select id="ibScen" class="nv-select"><option value="">-- Select Category --</option></select></div>';html+='<div class="int-controls"><span class="int-label">Intensity</span><span id="ibIntVal" style="min-width:36px;color:var(--accent)">50%</span><input type="range" id="ibInt" min="0" max="100" step="1" value="50" class="nv-slider" style="flex:1"></div>';
html+='<div class="int-override"><div class="int-controls"><span class="int-label" style="font-size:.75rem;color:var(--text2)">Override Style</span><select id="ibConflictOverride" class="nv-select" style="font-size:.78rem"><option value="">Use Default</option>';var confKeys=Object.keys(D.CONFLICT);for(var ci=0;ci<confKeys.length;ci++){html+='<option value="'+confKeys[ci]+'">'+D.CONFLICT[confKeys[ci]].label+'</option>';}html+='</select></div></div>';html+='<div class="int-controls"><button class="btn btn-primary" id="ibGo" disabled>\u26A1 Process</button></div>';
html+='<div class="response-chain" id="ibChain"><hr style="border:none;border-top:1px solid var(--border);margin:8px 0"><strong>\uD83D\uDD04 Response Chain</strong>';html+='<div class="int-controls"><span class="int-label">Direction</span><select id="ibChainDir" class="nv-select"><option value="AtoB">'+S.a.name+" \u2192 "+S.b.name+'</option><option value="BtoA">'+S.b.name+" \u2192 "+S.a.name+"</option></select></div>";html+='<div class="int-controls"><span class="int-label">Category</span><select id="ibChainCat" class="nv-select"><option value="">-- Select --</option></select></div>';html+='<div class="int-controls"><span class="int-label">Scenario</span><select id="ibChainScen" class="nv-select"><option value="">-- Select --</option></select></div>';html+='<div class="int-controls"><span class="int-label">Intensity</span><span id="ibChainIntVal" style="min-width:36px;color:var(--accent)">50%</span><input type="range" id="ibChainInt" min="0" max="100" step="1" value="50" class="nv-slider" style="flex:1"></div>';html+='<div class="int-controls"><button class="btn" id="ibChainGo" disabled>\uD83D\uDD04 Send Response</button></div></div>';
html+="</div>";return html;}
function buildPracTox(who){var s=who==="a"?"A":"B";var ph='<div class="section-title">\uD83D\uDCAA Personal Growth Activities</div><div class="prac-grid" id="pracGrid'+s+'">';for(var i=0;i<D.PERSONAL_POS.length;i++){ph+='<button class="btn btn-personal" data-who="'+who+'" data-idx="'+i+'">'+D.PERSONAL_POS[i].label+"</button>";}ph+="</div>";var th='<div class="section-title">\u2620 Personal Risk Behaviors</div><div class="toxic-grid" id="toxGrid'+s+'">';for(var i=0;i<D.PERSONAL_NEG.length;i++){th+='<button class="btn btn-personal-neg" data-who="'+who+'" data-idx="'+i+'">'+D.PERSONAL_NEG[i].label+"</button>";}th+="</div>";return '<div class="prac-tox-row"><div>'+ph+"</div><div>"+th+"</div></div>";}

function wpContent(){
var tabs=["Purpose","Models","Engine","Dimensions","Pipeline"];
var tabHtml='<div class="wp-tabs">';for(var i=0;i<tabs.length;i++){tabHtml+='<button class="wp-tab'+(i===0?" wp-tab-active":"")+'" data-tab="'+i+'">'+tabs[i]+"</button>";}tabHtml+="</div>";
var bodies=[];
bodies.push('<div class="wp-tab-body"><h2>Purpose & Philosophy</h2><p>Novus Love v3 is a <strong>systemic psychological dynamics engine</strong> \u2014 an educational simulation that models how two individuals interact, influence, and shape each other over time.</p><p>This tool integrates <strong>11 evidence-based psychological models</strong> into a unified system that calculates the ripple effects of every interaction. It reveals patterns that are invisible in the moment but transformative over time.</p><h3>A Tool is Neither Good Nor Evil</h3><p>Like any powerful instrument, Novus Love is neutral. Its value depends entirely on the <strong>intent of the person using it</strong>.</p><p>Used with care, it becomes a mirror \u2014 helping people understand their own patterns, recognize how their attachment style shapes their relationships, and see how small consistent actions compound into lasting change.</p><p>Used recklessly, it could reduce the beautiful complexity of human connection to numbers on a screen. That is not its purpose.</p><h3>What This Tool Can Do</h3><ul><li>Reveal hidden dynamics between attachment styles, communication patterns, and emotional regulation</li><li>Show how positive and negative interactions compound over time (Gottman 5:1 ratio)</li><li>Demonstrate how mental health factors ripple through relationships</li><li>Simulate the impact of repair attempts, boundary-setting, and vulnerability</li><li>Help users understand their own psychological patterns</li></ul><h3>What This Tool Cannot Do</h3><ul><li>Replace professional therapy or counseling</li><li>Diagnose mental health conditions</li><li>Predict real relationship outcomes with certainty</li><li>Capture the full depth of human emotional experience</li></ul><p><strong>If you are experiencing relationship distress, please consult a licensed mental health professional.</strong></p></div>');
bodies.push('<div class="wp-tab-body"><h2>Integrated Psychological Models</h2><table class="wp-table"><tr><th>Model</th><th>Weight</th><th>Key Contribution</th></tr><tr><td>Attachment Theory (Bowlby/Ainsworth)</td><td>0.28</td><td>Strongest single predictor of relationship quality</td></tr><tr><td>Gottman Method</td><td>0.22</td><td>Four Horsemen, repair, PSO/NSO, 5:1 ratio</td></tr><tr><td>Big Five / OCEAN</td><td>0.18</td><td>Most validated personality framework</td></tr><tr><td>Sternberg Triangle</td><td>0.10</td><td>Intimacy + Passion + Commitment = love type</td></tr><tr><td>Rusbult Investment Model</td><td>0.08</td><td>Commitment = Satisfaction + Investment - Alternatives</td></tr><tr><td>Bowen Differentiation of Self</td><td>0.06</td><td>Individual identity vs emotional fusion</td></tr><tr><td>Polyvagal Theory (Porges)</td><td>0.03</td><td>Nervous system states: ventral, sympathetic, dorsal</td></tr><tr><td>MBTI</td><td>0.02</td><td>Communication and cognitive style</td></tr><tr><td>Satir Communication Stances</td><td>0.01</td><td>Stress communication: placating, blaming, computing, distracting, congruent</td></tr><tr><td>Enneagram</td><td>0.01</td><td>Core motivational patterns</td></tr><tr><td>Circumplex Model of Affect</td><td>\u2014</td><td>Valence x Arousal mood mapping (modifier, no weight)</td></tr></table><h3>Why These Weights?</h3><p>Weights reflect empirical evidence strength. Attachment theory has the deepest research base for relationship outcomes. Gottman has 40+ years of observational data. OCEAN is the most replicated personality framework. MBTI and Enneagram carry less empirical weight but add meaningful texture.</p></div>');
bodies.push('<div class="wp-tab-body"><h2>Engine Architecture</h2><h3>Core Concepts</h3><p><strong>Vulnerability Scale (0.4\u20132.0x):</strong> How much a person is affected by incoming interactions. Driven by emotion regulation, self-worth, rejection sensitivity, external stress, neuroticism, and window of tolerance.</p><p><strong>Fragility Scale (0.4\u20132.0x):</strong> How much the relationship is affected. Driven by safety, trust, tension, friction, and conflict level.</p><p><strong>PSO/NSO:</strong> Positive or Negative Sentiment Override. Based on last 20 interactions. When positive (60%+), negative events are buffered 20%. When negative (40%-), negatives amplified 20% and positives dampened.</p><p><strong>Repair Window:</strong> After a negative event, a 3-event window opens. Repair attempts during this window are 2x effective.</p><p><strong>Behavior Frequency:</strong> Repeated behavior patterns escalate: 3x = 1.5 multiplier, 5x = 2.0 multiplier.</p><p><strong>Temporal Decay:</strong> Negative events have a half-life of 15 events; positive events decay with half-life of 5. Bad memories linger longer.</p><p><strong>Window of Tolerance (Polyvagal):</strong> Each person has a tolerance window derived from attachment, emotion regulation, and stress. Narrower windows mean faster dysregulation.</p><p><strong>Satir Stance:</strong> Communication posture under stress, derived from attachment style and current mood. Only congruent communication is healthy.</p></div>');
bodies.push('<div class="wp-tab-body"><h2>8-Dimension Radar</h2><p>Each person is profiled across 8 psychological dimensions, computed as a weighted overlay of all models:</p><table class="wp-table"><tr><th>Dimension</th><th>Description</th></tr><tr><td>Reactivity</td><td>Speed and intensity of emotional response</td></tr><tr><td>Withdrawal</td><td>Tendency to disengage under stress</td></tr><tr><td>Attunement</td><td>Ability to perceive partner emotional state</td></tr><tr><td>Growth</td><td>Capacity for positive change</td></tr><tr><td>Resilience</td><td>Bounce-back from stress and conflict</td></tr><tr><td>Expressiveness</td><td>Emotional communication ability</td></tr><tr><td>Self-Regulation</td><td>Impulse control and pause capacity</td></tr><tr><td>Adaptability</td><td>Flexibility in response to needs</td></tr></table></div>');
bodies.push('<div class="wp-tab-body"><h2>Engine Pipeline</h2><ol><li>Read profiles and configuration</li><li>Calculate Window of Tolerance for each person</li><li>Derive Satir communication stance</li><li>Determine Polyvagal state (ventral/sympathetic/dorsal)</li><li>Calculate vulnerability (receiver) and fragility (relationship)</li><li>Apply base effects x intensity x multipliers</li><li>Apply PSO/NSO sentiment override</li><li>Apply conflict style modifiers</li><li>Apply Satir stance effects on self, partner, and relationship</li><li>Apply Polyvagal state effects on relationship</li><li>Love Language compatibility bonus</li><li>Behavior frequency escalation check</li><li>Repair window check (2x if active)</li><li>Update Sternberg triangle (passion, intimacy)</li><li>Recalculate Rusbult commitment</li><li>Recalculate Bowen differentiation</li><li>Update health composites</li><li>Track attachment drift</li><li>Update conflict level and auto-mood</li><li>Log event and render</li></ol></div>');
var bHtml="";for(var i=0;i<bodies.length;i++){bHtml+='<div class="wp-body-panel" id="wpPanel'+i+'" style="display:'+(i===0?"block":"none")+'">'+bodies[i]+"</div>";}
return tabHtml+bHtml;}
function saveSession(){try{var d=E.clone(S);delete d.undoStack;localStorage.setItem("novus_v3_1",JSON.stringify(d));toast("Session saved.","pos");}catch(e){toast("Save failed.","neg");}}
function loadSession(){try{var raw=localStorage.getItem("novus_v3_1");if(!raw){toast("No saved session found.","info");return;}var d=JSON.parse(raw);Object.keys(d).forEach(function(k){S[k]=d[k];});S.undoStack=[];renderAll();toast("Session loaded.","pos");}catch(e){toast("Load failed.","neg");}}
function exportReport(){var lines=["NOVUS LOVE v3.1 \u2014 SESSION REPORT","Generated: "+new Date().toLocaleString(),"=".repeat(40)];lines.push("PERSON A: "+S.a.name+" | "+S.a.mbti+" | "+D.ATT[S.a.attach].label+" | Health: "+D.pct(S.a.health)+"%");lines.push("PERSON B: "+S.b.name+" | "+S.b.mbti+" | "+D.ATT[S.b.attach].label+" | Health: "+D.pct(S.b.health)+"%");lines.push("RELATIONSHIP: "+D.pct(S.rel.overall)+"% | "+D.getTier(S.rel.overall,D.REL_TIERS).label);var st=E.classifySternberg(S.rel.sternIntimacy,S.rel.passion,S.rel.commitment);lines.push("Love Type: "+st.type+" | Conflict: "+Math.round(S.conflictLvl)+"/6");lines.push("","EVENT LOG ("+S.log.length+")");for(var i=0;i<S.log.length;i++)lines.push("["+S.log[i].time+"] "+S.log[i].msg);var blob=new Blob([lines.join("\n")],{type:"text/plain"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download="novus-report-"+Date.now()+".txt";document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);}
function renderCompare(){var el=$("compareBody");if(!el)return;if(!S.snapshot){el.innerHTML="Take a snapshot first.";return;}var snap=S.snapshot;var h='<table class="wp-table"><tr><th>Metric</th><th>Snapshot</th><th>Current</th><th>Change</th></tr>';var rk=["safety","trust","bond","connection","meaning","honesty","stability","intimacy","growth","tension","friction","passion","commitment","sternIntimacy","overall"];for(var i=0;i<rk.length;i++){var k=rk[i];var old=snap.rel[k]||0;var cur=S.rel[k]||0;var diff=E.rnd(cur-old,3);var neg=k==="tension"||k==="friction";var clr=neg?(diff>0?"var(--neg)":diff<0?"var(--pos)":"var(--text2)"):(diff>0?"var(--pos)":diff<0?"var(--neg)":"var(--text2)");h+="<tr><td>"+D.friendly(k)+"</td><td>"+D.pct(old)+"%</td><td>"+D.pct(cur)+'%</td><td style="color:'+clr+'">'+(diff>0?"+":"")+D.pct(diff)+"%</td></tr>";}h+="</table>";el.innerHTML=h;}


function buildConfigModal(){var html='<div class="modal-overlay" id="configModal" style="display:none"><div class="modal config-modal"><h2 style="margin-bottom:12px;color:var(--accent)">\u2699 Engine Configuration</h2><p style="font-size:.82rem;color:var(--text2);margin-bottom:12px">Adjust the weight of each psychological model in the engine calculations. Total should equal 1.0.</p><div id="configRows"></div><div style="margin-top:12px;display:flex;gap:8px;justify-content:flex-end"><button class="btn" id="configResetBtn">Reset Defaults</button><button class="btn btn-primary" id="configCloseBtn">Close</button></div></div></div>';return html;}
function renderConfigRows(){var el=$("configRows");if(!el)return;var models=D.ENGINE_MODELS;if(!models)return;var html="";for(var i=0;i<models.length;i++){var m=models[i];var w=m.currentWeight!==undefined?m.currentWeight:m.defaultWeight;html+='<div class="config-row"><span class="config-label">'+m.label+'</span><input type="range" min="0" max="50" value="'+Math.round(w*100)+'" class="nv-slider config-slider" data-model="'+m.id+'" id="cfgW_'+m.id+'"><span class="config-val" id="cfgV_'+m.id+'">'+Math.round(w*100)+'%</span></div><div class="config-desc" style="padding:0 0 6px 148px">'+m.desc+'</div>';}el.innerHTML=html;document.querySelectorAll(".config-slider").forEach(function(sl){sl.addEventListener("input",function(){var id=this.getAttribute("data-model");var v=parseInt(this.value,10);var vEl=$("cfgV_"+id);if(vEl)vEl.textContent=v+"%";for(var j=0;j<D.ENGINE_MODELS.length;j++){if(D.ENGINE_MODELS[j].id===id)D.ENGINE_MODELS[j].currentWeight=v/100;}});});}
function wireConfigModal(){var btn=$("configBtn");if(btn)btn.addEventListener("click",function(){var m=$("configModal");if(m){m.style.display="flex";renderConfigRows();}});var cls=$("configCloseBtn");if(cls)cls.addEventListener("click",function(){$("configModal").style.display="none";});var rst=$("configResetBtn");if(rst)rst.addEventListener("click",function(){for(var i=0;i<D.ENGINE_MODELS.length;i++){D.ENGINE_MODELS[i].currentWeight=D.ENGINE_MODELS[i].defaultWeight;}renderConfigRows();});}

function buildDisclaimer(){return '<div class="modal-overlay" id="disclaimerModal"><div class="modal disclaimer-modal"><h2>\u2696\uFE0F Novus Love v3.1</h2><p>This is an <strong>educational simulation</strong> integrating 11 psychological models. It is <strong>not</strong> professional advice, therapy, or diagnosis.</p><p>Relationship dynamics are complex and cannot be fully captured by any model. If you are experiencing distress, please consult a licensed mental health professional.</p><div class="disclaimer-check-row"><input type="checkbox" id="discCB"><label for="discCB">I understand this is an educational tool and not professional advice.</label></div><div style="text-align:center;margin-top:12px"><button class="btn btn-primary" id="discBtn" disabled>I Understand</button></div></div></div>';}
function buildEventModal(){return '<div class="modal-overlay" id="eventModal" style="display:none"><div class="modal"><h3>\u26A1 Event Impact</h3><div id="eventBody"></div><div style="text-align:right;margin-top:10px"><button class="btn" id="closeEventModal">Close</button></div></div></div>';}
function buildCompareModal(){return '<div class="modal-overlay" id="compareModal" style="display:none"><div class="modal" style="max-width:560px"><h3>\uD83D\uDCCA Snapshot Comparison</h3><div id="compareBody"></div><div style="text-align:right;margin-top:10px"><button class="btn" id="closeCompareModal">Close</button></div></div></div>';}
function buildWhitepaperModal(){return '<div class="modal-overlay" id="wpModal" style="display:none"><div class="modal" style="max-width:680px;max-height:80vh;overflow-y:auto"><h3>\uD83D\uDCDA Whitepaper</h3><div id="wpContent">'+wpContent()+'</div><div style="text-align:right;margin-top:10px"><button class="btn" id="closeWPModal">Close</button></div></div></div>';}
function buildBottomBar(){return '<div class="bottom-bar"><button class="btn" id="btnUndo" data-tip="Undo last interaction">\u21A9 Undo</button><button class="btn" id="btnSnap" data-tip="Take a snapshot for comparison">\uD83D\uDCF8 Snap</button><button class="btn" id="btnCompare" data-tip="Compare current to snapshot">\uD83D\uDCCA Compare</button><button class="btn" id="btnSave" data-tip="Save session to browser">\uD83D\uDCBE Save</button><button class="btn" id="btnLoad" data-tip="Load saved session">\uD83D\uDCC2 Load</button><button class="btn" id="btnExport" data-tip="Download text report">\uD83D\uDCC4 Export</button><button class="btn" id="btnWP" data-tip="Open whitepaper">\uD83D\uDCDA Info</button><button class="btn" id="btnSound" data-tip="Toggle sound feedback">\uD83D\uDD0A Sound</button><button class="btn btn-neg" id="btnReset" data-tip="Reset session">\u26D4 Reset</button></div>';}
function renderAll(){var sbEl=$("statusBar");if(sbEl)sbEl.innerHTML=statusBarHTML();renderIndMetrics("a");renderIndMetrics("b");renderRelMetrics();renderStory("a");renderStory("b");renderNarrative();renderRecs();renderTimeline();renderLog("logAll",S.log);renderLog("logA",S.logA);renderLog("logB",S.logB);var rA=$("radarA");if(rA)rA.innerHTML=radarSVG("a");var rB=$("radarB");if(rB)rB.innerHTML=radarSVG("b");
var relRd=$("relRadarBox");if(relRd)relRd.innerHTML=relRadarSVG();
renderRecs();initTooltips();}
function readUI(){["a","b"].forEach(function(w){var s=w==="a"?"A":"B";var nm=$("name"+s);if(nm)S[w].name=nm.value||S[w].name;var mb=$("mbti"+s);if(mb&&mb.value)S[w].mbti=mb.value;var en=$("ennea"+s);if(en&&en.value)S[w].ennea=en.value;var at=$("attach"+s);if(at&&at.value)S[w].attach=at.value;var llg=$("llGive"+s);if(llg&&llg.value)S[w].llGive=llg.value;var llr=$("llReceive"+s);if(llr&&llr.value)S[w].llReceive=llr.value;var cs=$("conflict"+s);if(cs&&cs.value)S[w].conflict=cs.value;var md=$("mood"+s);if(md&&md.value)S[w].mood=md.value;var sp=$("support"+s);if(sp)S[w].support=parseInt(sp.value,10);
["O","C","E","A","N"].forEach(function(d){var sl=$("ocean_"+d+s);if(sl)S[w].ocean[d]=parseFloat(sl.value)/100;});
D.MH_ORDER.forEach(function(mk){var sl=$("mh_"+mk+s);if(sl)S[w].mh[mk]=parseInt(sl.value,10);});});}
function wireProfileChanges(){["a","b"].forEach(function(w){var s=w==="a"?"A":"B";["mbti"+s,"ennea"+s,"attach"+s,"llGive"+s,"llReceive"+s,"conflict"+s,"mood"+s].forEach(function(id){var el=$(id);if(!el)return;el.addEventListener("change",function(){readUI();if(id==="mbti"+s){E.setOceanFromMBTI(w);var oc=S[w].ocean;["O","C","E","A","N"].forEach(function(d){var sl=$("ocean_"+d+s);if(sl)sl.value=Math.round(oc[d.toLowerCase()]*100);var vl=$("ov_"+d+s);if(vl)vl.textContent=Math.round(oc[d]*100)+"%";});}E.recalcAll();renderAll();updateSelTips(w);});});
var supEl=$("support"+s);if(supEl){supEl.addEventListener("input",function(){var v=parseInt(this.value,10);S[w].support=v;var lbl=D.getSupportLabel(v);var valEl=$("supportVal"+s);if(valEl)valEl.textContent=lbl.label;var tipEl=$("supportTip"+s);if(tipEl)tipEl.textContent=lbl.desc;E.recalcAll();renderAll();});}

["O","C","E","A","N"].forEach(function(d){var sl=$("ocean_"+d+s);if(sl)sl.addEventListener("input",function(){var vl=$("ov_"+d+s);if(vl)vl.textContent=this.value+"%";readUI();E.recalcAll();renderAll();});});
D.MH_ORDER.forEach(function(mk){var sl=$("mh_"+mk+s);if(sl){sl.addEventListener("input",function(){var lv=parseInt(this.value,10);var info=D.MH_LEVELS[lv];var tip=$("mhtip_"+mk+s);if(tip)tip.textContent=info?info.label+" \u2014 "+info.desc:"";var mhv=$("mhval_"+mk+s);if(mhv)mhv.textContent=lv>0?info.label:"None";readUI();E.recalcAll();renderAll();});}});});}
function updateSelTips(w){var s=w==="a"?"A":"B";var maps=[{id:"mbti"+s,src:D.MBTI,key:S[w].mbti},{id:"ennea"+s,src:D.ENNEA,key:S[w].ennea},{id:"attach"+s,src:D.ATT,key:S[w].attach},{id:"mood"+s,src:D.MOOD,key:S[w].mood}];maps.forEach(function(m){var tip=$("tip_"+m.id);if(!tip)return;var d=m.src[m.key];if(d&&(d.desc||d.label)){tip.innerHTML='<span style="color:var(--text2);font-size:.72rem">'+(d.desc||d.label)+"</span>";tip.style.display="block";}else{tip.style.display="none";}});}
function wireInteractionBuilder(){var catEl=$("ibCat");var scenEl=$("ibScen");var intEl=$("ibInt");var intVal=$("ibIntVal");var goEl=$("ibGo");var chainEl=$("ibChain");var chainCatEl=$("ibChainCat");var chainScenEl=$("ibChainScen");var chainIntEl=$("ibChainInt");var chainIntValEl=$("ibChainIntVal");var chainGoEl=$("ibChainGo");
populateCats("ibCat");populateCats("ibChainCat");if(chainEl)chainEl.style.display="none";
if(catEl)catEl.addEventListener("change",function(){populateScens(catEl.value,"ibScen");if(goEl)goEl.disabled=true;if(chainEl)chainEl.style.display="none";});
if(scenEl)scenEl.addEventListener("change",function(){if(goEl)goEl.disabled=!scenEl.value;});
if(intEl)intEl.addEventListener("input",function(){if(intVal)intVal.textContent=intEl.value+"%";});
if(chainCatEl)chainCatEl.addEventListener("change",function(){populateScens(chainCatEl.value,"ibChainScen");if(chainGoEl)chainGoEl.disabled=true;});
if(chainScenEl)chainScenEl.addEventListener("change",function(){if(chainGoEl)chainGoEl.disabled=!chainScenEl.value;});
if(chainIntEl)chainIntEl.addEventListener("input",function(){if(chainIntValEl)chainIntValEl.textContent=chainIntEl.value+"%";});
if(goEl)goEl.addEventListener("click",function(){var dir=$("ibDir").value;var cat=catEl.value;var scIdx=parseInt(scenEl.value,10);var intensity=parseInt(intEl.value,10)/100;var result=E.processInteraction(dir,cat,scIdx,intensity);showEventSummary(result);renderAll();if(chainEl){chainEl.style.display="block";var autoDir=dir==="AtoB"?"BtoA":"AtoB";$("ibChainDir").value=autoDir;}});
if(chainGoEl)chainGoEl.addEventListener("click",function(){var dir=$("ibChainDir").value;var cat=chainCatEl.value;var scIdx=parseInt(chainScenEl.value,10);var intensity=parseInt(chainIntEl.value,10)/100;var result=E.processInteraction(dir,cat,scIdx,intensity);showEventSummary(result);renderAll();if(chainEl)chainEl.style.display="none";});}

function wirePracTox(){document.querySelectorAll(".btn-personal").forEach(function(b){b.addEventListener("click",function(){var w=this.dataset.who;var idx=parseInt(this.dataset.idx,10);E.processPersonal(w,D.PERSONAL_POS[idx].id,true);renderAll();toast(D.PERSONAL_POS[idx].label+" applied to "+S[w].name,"pos");});});document.querySelectorAll(".btn-personal-neg").forEach(function(b){b.addEventListener("click",function(){var w=this.dataset.who;var idx=parseInt(this.dataset.idx,10);E.processPersonal(w,D.PERSONAL_NEG[idx].id,false);renderAll();toast(D.PERSONAL_NEG[idx].label+" applied to "+S[w].name,"neg");});});}
function wireBottomBar(){var scEl=$("startCond");if(scEl){scEl.addEventListener("change",function(){S.startCond=this.value;E.applyStart();E.recalcAll();renderAll();toast("Starting state: "+D.START[this.value].label,"info");});}
$("btnUndo").addEventListener("click",function(){E.doUndo();renderAll();toast("Undo applied.","info");});$("btnSnap").addEventListener("click",function(){E.saveSnap();toast("Snapshot saved.","pos");});$("btnCompare").addEventListener("click",function(){renderCompare();$("compareModal").style.display="flex";});$("btnSave").addEventListener("click",saveSession);$("btnLoad").addEventListener("click",loadSession);$("btnExport").addEventListener("click",exportReport);$("btnWP").addEventListener("click",function(){$("wpModal").style.display="flex";});$("btnSound").addEventListener("click",function(){var on=E.toggleSound();var sb=this;if(on){sb.classList.add("sound-toggle");sb.classList.add("on");sb.classList.remove("off");sb.textContent="\uD83D\uDD0A Sound ON";}else{sb.classList.add("sound-toggle");sb.classList.remove("on");sb.classList.add("off");sb.textContent="\uD83D\uDD07 Sound OFF";}toast("Sound "+(on?"ON":"OFF"),"info");});$("btnReset").addEventListener("click",function(){if(confirm("Reset entire session?")){location.reload();}});}
function wireWPTabs(){document.querySelectorAll(".wp-tab").forEach(function(t){t.addEventListener("click",function(){document.querySelectorAll(".wp-tab").forEach(function(x){x.classList.remove("wp-tab-active");});t.classList.add("wp-tab-active");var idx=t.dataset.tab;document.querySelectorAll(".wp-body-panel").forEach(function(p){p.style.display="none";});var panel=$("wpPanel"+idx);if(panel)panel.style.display="block";});});}
function buildApp(){var app=$("app");if(!app)return;var html="";
html+='<header class="app-header"><h1>\u2764\uFE0F Novus Love <span class="version">v3.1</span></h1><p class="subtitle">Systemic Relationship Dynamics Engine \u2014 11 Psychological Models</p></header>';
html+='<div class="dashboard">';
html+='<div class="col col-person">';html+=accordion("\uD83D\uDC64 "+S.a.name+" \u2014 Profile","profA",buildProfilePanel("a")+'<div class="sub-acc"><div class="sub-acc-hd" onclick="var b=this.nextElementSibling;b.style.display=b.style.display===\'none\'?\'block\':\'none\';this.querySelector(\'span\').textContent=b.style.display===\'none\'?\'\u25B6\':\'\u25BC\';"><span>\u25B6</span> OCEAN Personality</div><div class="sub-acc-bd" style="display:none">'+buildOcean("a")+'</div></div><div class="sub-acc"><div class="sub-acc-hd" onclick="var b=this.nextElementSibling;b.style.display=b.style.display===\'none\'?\'block\':\'none\';this.querySelector(\'span\').textContent=b.style.display===\'none\'?\'\u25B6\':\'\u25BC\';"><span>\u25B6</span> Mental Health Factors</div><div class="sub-acc-bd" style="display:none">'+buildMH("a")+'</div></div>',true);html+=accordion("\uD83D\uDCCA "+S.a.name+" \u2014 Metrics","metricsA",'<div id="radarA">'+radarSVG("a")+'</div>'+buildIndMeters("a")+'<div id="dosA" class="info-card"></div><div id="driftA" class="info-card"></div><div id="satirA" class="info-card"></div><div id="vagalA" class="info-card"></div><div id="sentimentA" class="info-card"></div><div id="storyA" class="info-card"></div>');html+=accordion("\uD83D\uDCAA "+S.a.name+" \u2014 Activities","activA",buildPracTox("a"));html+='</div>';
html+='<div class="col col-rel">';html+='<div id="statusBar"></div>';html+='<div class="start-cond-row"><span class="field-label">Starting State</span><select id="startCond" class="nv-select">';var scKeys=Object.keys(D.START);for(var sci=0;sci<scKeys.length;sci++){var sck=scKeys[sci];html+='<option value="'+sck+'"'+(S.startCond===sck?' selected':'')+'>'+D.START[sck].label+'</option>';}html+='</select></div>';
html+=accordion("\u26A1 Interaction Builder","intBuild",buildInteractionPanel(),true);html+=accordion("\uD83D\uDCC8 Relationship Metrics","relMetrics",'<div class="section-title">Relationship Profile</div><div id="relRadarBox"></div>'+buildRelMeters()+'<div class="section-title" style="margin-top:8px">Emotional State</div><div id="relEmotState" class="info-card"></div><div id="relStatus" class="info-card" style="display:none"></div><div id="sternbergBox" class="info-card"></div><div id="rusbultBox" class="info-card" style="display:none"></div><div id="psoBox" class="info-card" style="display:none"></div><div id="repairBox" class="info-card" style="display:none"></div><div id="conflictBox" class="info-card" style="display:none"></div><div id="comboBox" class="info-card"></div>');html+=accordion("\uD83D\uDCDC Narrative","narr",'<div id="relNarrative" class="info-card"></div>');html+=accordion("\uD83D\uDCA1 Recommendations","recsAcc",'<div id="recs" class="info-card"></div>');html+=accordion("\uD83D\uDCC9 Timeline","tlAcc",'<div id="timelineBox"></div>');html+=accordion("\uD83D\uDCDD Event Log","logAcc",'<div class="log-tabs"><button class="log-tab log-tab-active" data-log="all">All</button><button class="log-tab" data-log="a">'+S.a.name+'</button><button class="log-tab" data-log="b">'+S.b.name+'</button></div><div id="logAll" class="log-box"></div><div id="logA" class="log-box" style="display:none"></div><div id="logB" class="log-box" style="display:none"></div>');html+='</div>';
html+='<div class="col col-person">';html+=accordion("\uD83D\uDC64 "+S.b.name+" \u2014 Profile","profB",buildProfilePanel("b")+'<div class="sub-acc"><div class="sub-acc-hd" onclick="var b=this.nextElementSibling;b.style.display=b.style.display===\'none\'?\'block\':\'none\';this.querySelector(\'span\').textContent=b.style.display===\'none\'?\'\u25B6\':\'\u25BC\';"><span>\u25B6</span> OCEAN Personality</div><div class="sub-acc-bd" style="display:none">'+buildOcean("b")+'</div></div><div class="sub-acc"><div class="sub-acc-hd" onclick="var b=this.nextElementSibling;b.style.display=b.style.display===\'none\'?\'block\':\'none\';this.querySelector(\'span\').textContent=b.style.display===\'none\'?\'\u25B6\':\'\u25BC\';"><span>\u25B6</span> Mental Health Factors</div><div class="sub-acc-bd" style="display:none">'+buildMH("b")+'</div></div>',true);html+=accordion("\uD83D\uDCCA "+S.b.name+" \u2014 Metrics","metricsB",'<div id="radarB">'+radarSVG("b")+'</div>'+buildIndMeters("b")+'<div id="dosB" class="info-card"></div><div id="driftB" class="info-card"></div><div id="satirB" class="info-card"></div><div id="vagalB" class="info-card"></div><div id="sentimentB" class="info-card"></div><div id="storyB" class="info-card"></div>');html+=accordion("\uD83D\uDCAA "+S.b.name+" \u2014 Activities","activB",buildPracTox("b"));html+='</div>';
html+='</div>';
html+=buildBottomBar();html+=buildConfigModal()+buildDisclaimer();html+=buildEventModal();html+=buildCompareModal();html+=buildWhitepaperModal();
html+='<div class="modal-overlay" id="wizModal" style="display:none"><div class="modal wiz-modal"><h3 id="wizTitle">\uD83E\uDDD9 Setup Wizard</h3><div class="wiz-progress" id="wizProgress"></div><div id="wizBody"></div><div class="wiz-nav"><button class="btn" id="wizPrev" disabled>\u2190 Back</button><button class="btn btn-primary" id="wizNext">Next \u2192</button></div></div></div>';
app.innerHTML=html;}
function wireLogTabs(){document.querySelectorAll(".log-tab").forEach(function(t){t.addEventListener("click",function(){document.querySelectorAll(".log-tab").forEach(function(x){x.classList.remove("log-tab-active");});t.classList.add("log-tab-active");var which=t.dataset.log;["logAll","logA","logB"].forEach(function(id){var el=$(id);if(el)el.style.display="none";});var target=which==="all"?"logAll":which==="a"?"logA":"logB";var el=$(target);if(el)el.style.display="block";});});}

function wireModalClose(){["eventModal","compareModal","wpModal"].forEach(function(mid){var closeId="close"+mid.charAt(0).toUpperCase()+mid.slice(1);var closeBtn=$(closeId.replace("Modal","Modal"));if(!closeBtn){var btn=document.getElementById("close"+mid.replace("m","M").replace("odal","odal"));if(btn)btn.addEventListener("click",function(){$(mid).style.display="none";});}});var ce=$("closeEventModal");if(ce)ce.addEventListener("click",function(){$("eventModal").style.display="none";});var cc=$("closeCompareModal");if(cc)cc.addEventListener("click",function(){$("compareModal").style.display="none";});var cw=$("closeWPModal");if(cw)cw.addEventListener("click",function(){$("wpModal").style.display="none";});}

function initApp(){buildApp();var discCB=$("discCB");var discBtn=$("discBtn");if(discCB&&discBtn){discCB.addEventListener("change",function(){discBtn.disabled=!discCB.checked;});discBtn.addEventListener("click",function(){$("disclaimerModal").style.display="none";});}initAccordions();initTooltips();wireProfileChanges();wireInteractionBuilder();wirePracTox();wireBottomBar();wireWPTabs();wireLogTabs();wireModalClose();wireConfigModal();
function wireWizard(){
var wizState={who:null,field:null,step:0,steps:[],scores:{},results:{}};
function openWiz(who,field){wizState.who=who;wizState.field=field;wizState.step=0;wizState.scores={};wizState.results={};
var fields=field?[field]:["mbti","ennea","attach","llGive","conflict","mood","support"];
wizState.steps=[];
for(var i=0;i<fields.length;i++){var f=fields[i];var wKey=f==="ennea"?"ENNEA":f==="attach"?"ATTACH":f==="llGive"||f==="llReceive"?"LL":f==="conflict"?"CONFLICT":f==="mood"?"MOOD":f==="support"?"SUPPORT":f.toUpperCase();
if(D.WIZARD[wKey])wizState.steps.push({field:f,key:wKey,data:D.WIZARD[wKey]});}
if(!wizState.steps.length){N.toast("No wizard available for this field.","info");return;}
$("wizModal").style.display="flex";renderWizStep();}
function renderWizStep(){var st=wizState.steps[wizState.step];if(!st)return;
var prog="";for(var i=0;i<wizState.steps.length;i++){var cls=i<wizState.step?"wiz-dot wiz-dot-done":i===wizState.step?"wiz-dot wiz-dot-active":"wiz-dot";prog+='<div class="'+cls+'"></div>';}$("wizProgress").innerHTML=prog;
$("wizTitle").textContent="\uD83E\uDDD9 "+st.data.title;
var html='<div class="wiz-step"><p>'+st.data.desc+"</p>";
if(!wizState.scores[st.key])wizState.scores[st.key]={};
var qs=st.data.questions;for(var qi=0;qi<qs.length;qi++){html+='<div class="wiz-question"><p>'+(qi+1)+". "+qs[qi].q+'</p><div class="wiz-options">';
for(var ai=0;ai<qs[qi].a.length;ai++){var sel=wizState.scores[st.key]["q"+qi]===ai?"selected":"";html+='<div class="wiz-opt '+sel+'" data-qkey="'+st.key+'" data-qi="'+qi+'" data-ai="'+ai+'">'+qs[qi].a[ai].text+"</div>";}html+="</div></div>";}
html+="</div>";
if(wizState.results[st.key]){var res=wizState.results[st.key];html+='<div class="wiz-result"><h4>Your Result: '+res.label+'</h4><p>'+res.summary+"</p></div>";}
$("wizBody").innerHTML=html;
$("wizPrev").disabled=wizState.step===0;
$("wizNext").textContent=wizState.step>=wizState.steps.length-1?"\u2713 Finish":"Next \u2192";
document.querySelectorAll(".wiz-opt").forEach(function(o){o.addEventListener("click",function(){var qkey=this.dataset.qkey;var qi=parseInt(this.dataset.qi);var ai=parseInt(this.dataset.ai);wizState.scores[qkey]["q"+qi]=ai;
this.parentElement.querySelectorAll(".wiz-opt").forEach(function(x){x.classList.remove("selected");});this.classList.add("selected");
var st2=wizState.steps[wizState.step];var allAnswered=true;for(var i=0;i<st2.data.questions.length;i++){if(wizState.scores[st2.key]["q"+i]===undefined){allAnswered=false;break;}}
if(allAnswered){var totals={};for(var i=0;i<st2.data.questions.length;i++){var chosen=wizState.scores[st2.key]["q"+i];var scoreObj=st2.data.questions[i].a[chosen].score;for(var sk in scoreObj){totals[sk]=(totals[sk]||0)+scoreObj[sk];}}
var result=st2.data.resolve(totals);wizState.results[st2.key]={value:result};
var lbl="";var summary="";
if(st2.key==="MBTI"){lbl=D.MBTI[result]?D.MBTI[result].label:result;summary=D.WIZARD.SUMMARIES.MBTI?D.WIZARD.SUMMARIES.MBTI(result):"";}
else if(st2.key==="ENNEA"){lbl=D.ENNEA[result]?D.ENNEA[result].label:result;summary=D.WIZARD.SUMMARIES.ENNEA?D.WIZARD.SUMMARIES.ENNEA(result):"";}
else if(st2.key==="ATTACH"){lbl=D.ATT[result]?D.ATT[result].label:result;summary=D.WIZARD.SUMMARIES.ATTACH?D.WIZARD.SUMMARIES.ATTACH(result):"";}
else if(st2.key==="LL"){lbl=D.LL_LABELS?D.LL_LABELS[result]||result:result;summary="This is how you naturally express or prefer to receive love.";}
else if(st2.key==="CONFLICT"){lbl=D.CONFLICT[result]?D.CONFLICT[result].label:result;summary="Your default approach to disagreements. This affects how conflicts are processed in the engine.";}
else if(st2.key==="MOOD"){lbl=result.charAt(0).toUpperCase()+result.slice(1);summary="Your current emotional state temporarily influences all interactions.";}
else if(st2.key==="SUPPORT"){lbl=D.getSupportLabel?D.getSupportLabel(result).label:result+"";summary=D.getSupportLabel?D.getSupportLabel(result).desc:"";}
wizState.results[st2.key].label=lbl;wizState.results[st2.key].summary=summary;
renderWizStep();}});});}
$("wizNext").addEventListener("click",function(){var st=wizState.steps[wizState.step];if(wizState.results[st.key]){var val=wizState.results[st.key].value;var who=wizState.who;var s=who==="a"?"A":"B";var field=st.field;
if(field==="mbti"){S[who].mbti=val;var el=$("mbti"+s);if(el)el.value=val;E.setOceanFromMBTI(who);}
else if(field==="ennea"){S[who].ennea=val;var el=$("ennea"+s);if(el)el.value=val;}
else if(field==="attach"){S[who].attach=val;var el=$("attach"+s);if(el)el.value=val;}
else if(field==="llGive"||field==="llReceive"){S[who][field]=val;var el=$(field+s);if(el)el.value=val;}
else if(field==="conflict"){S[who].conflict=val;var el=$("conflict"+s);if(el)el.value=val;}
else if(field==="mood"){S[who].mood=val;var el=$("mood"+s);if(el)el.value=val;}
else if(field==="support"){S[who].support=typeof val==="number"?val:50;var el=$("support"+s);if(el)el.value=S[who].support;}}
if(wizState.step<wizState.steps.length-1){wizState.step++;renderWizStep();}else{$("wizModal").style.display="none";E.recalcAll();renderAll();updateSelTips(wizState.who);N.toast("Wizard complete! Profile updated.","pos");}});
$("wizPrev").addEventListener("click",function(){if(wizState.step>0){wizState.step--;renderWizStep();}});
document.querySelectorAll(".wiz-top-btn").forEach(function(b){b.addEventListener("click",function(){openWiz(this.dataset.who,null);});});
N.openWizField=openWiz;}

wireWizard();E.applyStart();E.initEngine();renderAll();updateSelTips("a");updateSelTips("b");}
document.addEventListener("DOMContentLoaded",initApp);
})(window.Novus=window.Novus||{});
